project_id = "imkpdqtjfgxblvzdlvjc"

[functions]
  [functions.assign-church-admin]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-daily-content]
    verify_jwt = false
  [functions.get-user-email]
    verify_jwt = false
  [functions.process-sermon]
    verify_jwt = false
  [functions.send-admin-invite]
    verify_jwt = false
  [functions.send-push]
    verify_jwt = false
  [functions.upload-sermon]
    verify_jwt = false
