/**
 * Demo/hardcoded data used when ?demo=true is active.
 * This keeps the app showable without real database content.
 */

export const DEMO_SERMON = {
  id: "demo-sermon-1",
  title: "Grace in the Storm",
  date: "February 7, 2026",
  subtitle: "Finding peace amid uncertainty",
  speaker: "Pastor James Whitfield",
  church: "Cornerstone Community Church",
  duration: "48:32",
  videoUrl: null as string | null,
  sourceUrl: null as string | null,
  sourceType: "upload" as const,
  thumbnailUrl: null as string | null,
  storagePath: null as string | null,
  chapters: [
    { title: "Introduction", timestamp: "00:00" },
    { title: "The Story of Peter", timestamp: "07:12" },
    { title: "When the Storm Hits", timestamp: "14:45" },
    { title: "Grace as an Anchor", timestamp: "22:30" },
    { title: "Practical Steps Forward", timestamp: "35:18" },
    { title: "Closing Prayer", timestamp: "44:00" },
  ],
  scriptures: [
    {
      reference: "Matthew 14:27–31",
      text: '"Take courage! It is I. Don\'t be afraid." … "Lord, save me!" Immediately Jesus reached out his hand and caught him.',
    },
    {
      reference: "Ephesians 2:8–9",
      text: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.",
    },
    {
      reference: "Romans 8:28",
      text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    },
  ],
  takeaways: [
    "Grace is not earned — it is a gift that meets us in our storms, not after them.",
    "Like Peter, our eyes fix on the waves instead of Jesus. Refocusing is a daily discipline.",
    "Peace isn't the absence of storms; it's the presence of God within them.",
    "Every storm has a purpose — God uses uncertainty to deepen our trust.",
    "Community is part of God's design for resilience. Don't face the storm alone.",
  ],
  reflectionQuestions: [
    "What is one thing you're holding onto this week that you could trust God with instead?",
    "Think of a past storm that God brought you through. How did that season shape your faith?",
    "In what area of your life do you need to shift your focus from the waves to Jesus this week?",
    "How does knowing grace is a gift — not earned — change the way you approach God when you feel like you've failed?",
    "Who in your community is in a storm right now? How can you reach out to them this week?",
  ],
  spark: "Grace meets you in the storm, not on the other side of it.",
  weeklyChallenge:
    "This week, write down one fear that's been keeping you from trusting God fully. Then write a verse of scripture next to it — a promise that speaks directly to that fear.",
  weekendReflection:
    "Look back on this week — what has God been teaching you through this sermon?",
};

export const DEMO_PREVIOUS_SERMONS: typeof DEMO_SERMON[] = [
  {
    id: "demo-sermon-2",
    title: "You Are Already Enough",
    date: "January 31, 2026",
    subtitle: "Resting in your God-given identity",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "42:15",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    thumbnailUrl: null,
    storagePath: null,
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "The Lie of Performance", timestamp: "06:30" },
      { title: "What God Says About You", timestamp: "13:20" },
      { title: "Replacing the Lies", timestamp: "24:00" },
      { title: "Closing Prayer", timestamp: "38:45" },
    ],
    scriptures: [
      { reference: "Psalm 139:14", text: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well." },
      { reference: "Ephesians 1:4–5", text: "For he chose us in him before the creation of the world to be holy and blameless in his sight. In love he predestined us for adoption." },
    ],
    takeaways: [
      "Your identity is not determined by what you do, but by Whose you are.",
      "Performance-based faith exhausts us — grace invites us to rest.",
      "Replacing lies with scripture is a daily, intentional practice.",
      "God's love is not conditional on your productivity or success.",
    ],
    reflectionQuestions: [
      "Where are you striving to earn something God has already freely given?",
      "What lie about your identity have you been believing? What does scripture say instead?",
      "How would your week look different if you truly believed you were enough?",
    ],
    spark: "You don't have to earn what God has already freely given.",
    weeklyChallenge: "Write down one lie you've believed about yourself, then find a verse that speaks the truth. Read it aloud every morning this week.",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
  {
    id: "demo-sermon-3",
    title: "The Power of Small Steps",
    date: "January 24, 2026",
    subtitle: "Faithfulness in the everyday moments",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "39:50",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    thumbnailUrl: null,
    storagePath: null,
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "David & Goliath Revisited", timestamp: "05:00" },
      { title: "Small Obediences", timestamp: "12:40" },
      { title: "Building Momentum", timestamp: "22:15" },
      { title: "Closing Prayer", timestamp: "36:00" },
    ],
    scriptures: [
      { reference: "Zechariah 4:10", text: "Do not despise these small beginnings, for the LORD rejoices to see the work begin." },
      { reference: "Luke 16:10", text: "Whoever can be trusted with very little can also be trusted with much." },
    ],
    takeaways: [
      "God is not looking for grand gestures — He is looking for faithful small steps.",
      "Every small act of obedience builds trust between you and God.",
      "Don't wait for the perfect moment. Start where you are.",
      "Momentum is built one faithful decision at a time.",
    ],
    reflectionQuestions: [
      "What small step of obedience have you been putting off?",
      "Where in your life are you waiting for a 'big moment' instead of being faithful now?",
      "How can you celebrate small wins with God this week?",
    ],
    spark: "Don't despise small beginnings — God starts big things in small places.",
    weeklyChallenge: "Identify one small spiritual habit — 5 minutes of prayer, one verse a day — and do it every day this week without skipping.",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
  {
    id: "demo-sermon-4",
    title: "When God Feels Distant",
    date: "January 17, 2026",
    subtitle: "Navigating seasons of spiritual dryness",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "45:00",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    thumbnailUrl: null,
    storagePath: null,
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "The Psalms of Lament", timestamp: "08:00" },
      { title: "Spiritual Dryness is Normal", timestamp: "17:30" },
      { title: "Practices That Draw Us Near", timestamp: "28:00" },
      { title: "Closing Prayer", timestamp: "41:00" },
    ],
    scriptures: [
      { reference: "Psalm 22:1", text: "My God, my God, why have you forsaken me? Why are you so far from saving me, so far from my cries of anguish?" },
      { reference: "James 4:8", text: "Come near to God and he will come near to you." },
    ],
    takeaways: [
      "Feeling distant from God is not evidence that He has left — it is an invitation to draw near.",
      "The Psalms give us permission to be honest with God in every season.",
      "Spiritual disciplines are not about earning God's presence — they create space to receive it.",
      "Dry seasons often precede breakthrough seasons.",
    ],
    reflectionQuestions: [
      "Are you in a dry season right now? What does it feel like?",
      "What practice could you add this week to draw nearer to God?",
      "How have past dry seasons shaped your faith in ways you didn't expect?",
    ],
    spark: "God has not moved. He is closer than you think.",
    weeklyChallenge: "Spend 10 minutes in silence each morning this week — no music, no phone — just sitting with God and letting Him speak.",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
  {
    id: "demo-sermon-5",
    title: "Forgiveness Is a Practice",
    date: "January 10, 2026",
    subtitle: "Learning to release what we were never meant to carry",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "51:20",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    thumbnailUrl: null,
    storagePath: null,
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "The Weight of Unforgiveness", timestamp: "07:00" },
      { title: "The Parable of the Prodigal Son", timestamp: "15:00" },
      { title: "Forgiveness is Not Excusing", timestamp: "28:00" },
      { title: "Steps Toward Freedom", timestamp: "40:00" },
      { title: "Closing Prayer", timestamp: "48:00" },
    ],
    scriptures: [
      { reference: "Ephesians 4:31–32", text: "Get rid of all bitterness, rage and anger… Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you." },
      { reference: "Matthew 6:14", text: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you." },
    ],
    takeaways: [
      "Unforgiveness is a weight we were never designed to carry.",
      "Forgiveness is not excusing the wrong — it is releasing your right to revenge.",
      "You may need to choose forgiveness daily before it becomes a feeling.",
      "Forgiving others is an act of trusting God with justice.",
    ],
    reflectionQuestions: [
      "Is there someone in your life you haven't fully forgiven?",
      "What would it feel like to release that person to God today?",
      "How has God's forgiveness of you changed the way you see others?",
    ],
    spark: "Forgiveness is not a feeling — it's a decision to stop carrying what God never asked you to hold.",
    weeklyChallenge: "Write a letter to someone you need to forgive — you don't have to send it. Just write what you felt and then write: 'I release this to God.'",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
];

export const DEMO_JOURNAL_ENTRIES = [
  {
    id: "1",
    date: "Feb 10, 2026",
    type: "reflection" as const,
    tag: "Daily Reflection",
    preview: "The part about Peter stepping out of the boat really stayed with me. I've been clinging to the boat in my own life — staying safe instead of trusting...",
    sermonTitle: "Grace in the Storm",
    bookmarked: true,
    fullText: "The part about Peter stepping out of the boat really stayed with me. I've been clinging to the boat in my own life — staying safe instead of trusting God with the uncertainty. Pastor James asked where we're looking, and I realized I've been staring at the waves of my job situation. Today I'm choosing to look up.",
    suggestedScripture: {
      reference: "Matthew 14:29",
      text: '"Come," he said. Then Peter got down out of the boat, walked on the water and came toward Jesus.',
    },
  },
  {
    id: "2",
    date: "Feb 8, 2026",
    type: "reflection" as const,
    tag: "Daily Reflection",
    preview: "I wrote down my fear: 'That I'm not enough.' Next to it I put Romans 8:38–39. I read it three times and something...",
    sermonTitle: "Grace in the Storm",
    bookmarked: false,
    fullText: "I wrote down my fear: 'That I'm not enough.' Next to it I put Romans 8:38–39. I read it three times and something shifted. I am convinced that nothing in all creation can separate me from the love of God. That's not me — that's the Word. I'm holding onto this.",
    suggestedScripture: {
      reference: "Romans 8:38–39",
      text: "For I am convinced that neither death nor life, neither angels nor demons… shall be able to separate us from the love of God.",
    },
  },
  {
    id: "3",
    date: "Jan 31, 2026",
    type: "reflection" as const,
    tag: "Daily Reflection",
    preview: "The series on identity hit differently this week. I keep performing for God instead of resting in who He says I am. Working on it...",
    sermonTitle: "You Are Already Enough",
    bookmarked: true,
    fullText: "The series on identity hit differently this week. I keep performing for God instead of resting in who He says I am. Working on replacing the lies with truth — one day at a time.",
    suggestedScripture: {
      reference: "Psalm 139:14",
      text: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.",
    },
  },
  {
    id: "4",
    date: "Feb 9, 2026",
    type: "personal" as const,
    tag: "Personal",
    preview: "Grateful for the quiet this morning. Made coffee, sat on the porch, and just breathed. No agenda, no rush. It felt like prayer without words...",
    sermonTitle: "Morning Gratitude",
    bookmarked: false,
    fullText: "Grateful for the quiet this morning. Made coffee, sat on the porch, and just breathed. No agenda, no rush. It felt like prayer without words. I want more mornings like this — unhurried and present. Thank You, God, for the stillness.",
  },
  {
    id: "5",
    date: "Feb 5, 2026",
    type: "personal" as const,
    tag: "Personal",
    preview: "Had a hard conversation with a friend today. I didn't handle it perfectly, but I stayed honest. That feels like growth...",
    sermonTitle: "Honest Conversations",
    bookmarked: false,
    fullText: "Had a hard conversation with a friend today. I didn't handle it perfectly, but I stayed honest. That feels like growth. A year ago I would have avoided it entirely. God, help me keep choosing truth over comfort — even when it's messy.",
  },
];

export const DEMO_COMMUNITY_PULSE = {
  recent_reflectors: [
    { first_name: "Marcus", avatar_url: null as string | null, reflected_at: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
    { first_name: "Rachel", avatar_url: null as string | null, reflected_at: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
    { first_name: "David", avatar_url: null as string | null, reflected_at: new Date(Date.now() - 1000 * 60 * 120).toISOString() },
  ],
  recent_milestones: [
    { first_name: "Sarah", avatar_url: null as string | null, milestone: 10, earned_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString() },
    { first_name: "James", avatar_url: null as string | null, milestone: 5, earned_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString() },
  ],
  recent_members: [
    { first_name: "Emily", avatar_url: null as string | null, joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
  ],
  recent_likes: [
    { first_name: "David", avatar_url: null as string | null, target_type: "sermon", liked_at: new Date(Date.now() - 1000 * 60 * 15).toISOString() },
    { first_name: "Rachel", avatar_url: null as string | null, target_type: "takeaway", liked_at: new Date(Date.now() - 1000 * 60 * 45).toISOString() },
  ],
  active_avatars: [
    { avatar_url: null as string | null, first_name: "Marcus" },
    { avatar_url: null as string | null, first_name: "Sarah" },
    { avatar_url: null as string | null, first_name: "Emily" },
    { avatar_url: null as string | null, first_name: "David" },
  ],
};

export const DEMO_GROUPS = [
  {
    id: "demo-group-womens",
    name: "Women's Group",
    description: "A space for women to connect, share, and grow in faith together.",
    memberCount: 14,
    isMember: true,
    hasUnread: false,
  },
  {
    id: "demo-group-mens",
    name: "Men's Group",
    description: "Brotherhood, accountability, and Christ-centered conversations.",
    memberCount: 11,
    isMember: false,
    hasUnread: false,
  },
  {
    id: "demo-group-couples",
    name: "Married Couples",
    description: "Strengthening marriages through faith, fellowship, and fun.",
    memberCount: 8,
    isMember: false,
    hasUnread: false,
  },
];

/** Demo group members keyed by group id */
export const DEMO_GROUP_MEMBERS: Record<string, { userId: string; firstName: string; lastName: string; username: string; avatarUrl: string | null }[]> = {
  "demo-group-womens": [
    { userId: "demo-sarah", firstName: "Sarah", lastName: "Mitchell", username: "sarah_m", avatarUrl: null },
    { userId: "demo-grace", firstName: "Grace", lastName: "Obi", username: "grace_obi", avatarUrl: null },
    { userId: "demo-rachel", firstName: "Rachel", lastName: "Henderson", username: "rachel_h", avatarUrl: null },
    { userId: "demo-angela", firstName: "Angela", lastName: "Rivera", username: "angela_r", avatarUrl: null },
    { userId: "demo-faith", firstName: "Faith", lastName: "Nwosu", username: "faith_n", avatarUrl: null },
    { userId: "demo-naomi", firstName: "Naomi", lastName: "Williams", username: "naomi_w", avatarUrl: null },
    { userId: "demo-priya", firstName: "Priya", lastName: "Desai", username: "priya_d", avatarUrl: null },
    { userId: "demo-maya", firstName: "Maya", lastName: "Thompson", username: "maya_t", avatarUrl: null },
    { userId: "demo-abigail", firstName: "Abigail", lastName: "Clark", username: "abigail_c", avatarUrl: null },
    { userId: "demo-olivia", firstName: "Olivia", lastName: "Jackson", username: "olivia_j", avatarUrl: null },
    { userId: "demo-chloe", firstName: "Chloe", lastName: "Brown", username: "chloe_b", avatarUrl: null },
    { userId: "demo-zoe", firstName: "Zoe", lastName: "Foster", username: "zoe_f", avatarUrl: null },
    { userId: "demo-esther", firstName: "Esther", lastName: "Okonkwo", username: "esther_o", avatarUrl: null },
    { userId: "demo-hannah", firstName: "Hannah", lastName: "Lopez", username: "hannah_l", avatarUrl: null },
  ],
  "demo-group-mens": [
    { userId: "demo-james", firstName: "James", lastName: "Whitfield", username: "pastor_james", avatarUrl: null },
    { userId: "demo-david", firstName: "David", lastName: "Chen", username: "david.chen", avatarUrl: null },
    { userId: "demo-marcus", firstName: "Marcus", lastName: "Johnson", username: "marcus_j", avatarUrl: null },
    { userId: "demo-joshua", firstName: "Joshua", lastName: "Brooks", username: "joshua_b", avatarUrl: null },
    { userId: "demo-tyler", firstName: "Tyler", lastName: "Kim", username: "tyler_k", avatarUrl: null },
    { userId: "demo-caleb", firstName: "Caleb", lastName: "Stewart", username: "caleb_s", avatarUrl: null },
    { userId: "demo-ethan", firstName: "Ethan", lastName: "Lewis", username: "ethan_l", avatarUrl: null },
    { userId: "demo-daniel", firstName: "Daniel", lastName: "Garcia", username: "daniel_g", avatarUrl: null },
    { userId: "demo-isaiah", firstName: "Isaiah", lastName: "Moore", username: "isaiah_m", avatarUrl: null },
    { userId: "demo-noah", firstName: "Noah", lastName: "Anderson", username: "noah_a", avatarUrl: null },
    { userId: "demo-liam", firstName: "Liam", lastName: "Harris", username: "liam_h", avatarUrl: null },
  ],
  "demo-group-couples": [
    { userId: "demo-sarah", firstName: "Sarah", lastName: "Mitchell", username: "sarah_m", avatarUrl: null },
    { userId: "demo-david", firstName: "David", lastName: "Chen", username: "david.chen", avatarUrl: null },
    { userId: "demo-rachel", firstName: "Rachel", lastName: "Henderson", username: "rachel_h", avatarUrl: null },
    { userId: "demo-mike", firstName: "Michael", lastName: "Patterson", username: "mike_p", avatarUrl: null },
    { userId: "demo-ruth", firstName: "Ruth", lastName: "Phillips", username: "ruth_p", avatarUrl: null },
    { userId: "demo-samuel", firstName: "Samuel", lastName: "Nguyen", username: "samuel_n", avatarUrl: null },
    { userId: "demo-miriam", firstName: "Miriam", lastName: "Davis", username: "miriam_d", avatarUrl: null },
    { userId: "demo-aaron", firstName: "Aaron", lastName: "Robinson", username: "aaron_r", avatarUrl: null },
  ],
};

/** Demo chat messages keyed by group id */
export const DEMO_GROUP_MESSAGES: Record<string, { id: string; user_id: string; content: string; created_at: string; sender: { first_name: string; last_name: string; avatar_url: string | null } }[]> = {
  "demo-group-womens": [
    { id: "wm1", user_id: "demo-sarah", content: "Good morning everyone! 🌸 Hope you all had a restful weekend.", created_at: "2026-02-25T09:14:00Z", sender: { first_name: "Sarah", last_name: "Mitchell", avatar_url: null } },
    { id: "wm2", user_id: "demo-grace", content: "Morning Sarah! It was so good. We finally tried that new brunch spot after church 😄", created_at: "2026-02-25T09:18:00Z", sender: { first_name: "Grace", last_name: "Obi", avatar_url: null } },
    { id: "wm3", user_id: "demo-rachel", content: "Oh which one?? I've been wanting to try somewhere new", created_at: "2026-02-25T09:20:00Z", sender: { first_name: "Rachel", last_name: "Henderson", avatar_url: null } },
    { id: "wm4", user_id: "demo-grace", content: "The Fig & Olive on Main St! The avocado toast is 🔥", created_at: "2026-02-25T09:22:00Z", sender: { first_name: "Grace", last_name: "Obi", avatar_url: null } },
    { id: "wm5", user_id: "demo-faith", content: "Ladies, did anyone else get hit hard by Sunday's sermon? I keep going back to that part about grace meeting us in the storm.", created_at: "2026-02-25T10:05:00Z", sender: { first_name: "Faith", last_name: "Nwosu", avatar_url: null } },
    { id: "wm6", user_id: "demo-naomi", content: "YES. I literally wrote that whole section down in my journal. So needed.", created_at: "2026-02-25T10:12:00Z", sender: { first_name: "Naomi", last_name: "Williams", avatar_url: null } },
    { id: "wm7", user_id: "demo-sarah", content: "Same here. I've been going through a tough season at work and it just felt like God was speaking directly to me.", created_at: "2026-02-25T10:18:00Z", sender: { first_name: "Sarah", last_name: "Mitchell", avatar_url: null } },
    { id: "wm8", user_id: "demo-maya", content: "Praying for you Sarah 💛 You're not alone in this!", created_at: "2026-02-25T10:22:00Z", sender: { first_name: "Maya", last_name: "Thompson", avatar_url: null } },
    { id: "wm9", user_id: "demo-olivia", content: "Are we still doing coffee this Thursday? I can book the back room at Blue Door.", created_at: "2026-02-25T14:30:00Z", sender: { first_name: "Olivia", last_name: "Jackson", avatar_url: null } },
    { id: "wm10", user_id: "demo-abigail", content: "I'm in! 🙋‍♀️", created_at: "2026-02-25T14:35:00Z", sender: { first_name: "Abigail", last_name: "Clark", avatar_url: null } },
    { id: "wm11", user_id: "demo-grace", content: "Count me in too!", created_at: "2026-02-25T14:38:00Z", sender: { first_name: "Grace", last_name: "Obi", avatar_url: null } },
    { id: "wm12", user_id: "demo-hannah", content: "Same! What time works for everyone?", created_at: "2026-02-25T14:45:00Z", sender: { first_name: "Hannah", last_name: "Lopez", avatar_url: null } },
    { id: "wm13", user_id: "demo-olivia", content: "How about 7pm? After the kids are settled 😅", created_at: "2026-02-25T14:50:00Z", sender: { first_name: "Olivia", last_name: "Jackson", avatar_url: null } },
    { id: "wm14", user_id: "demo-zoe", content: "Perfect. See you all there! 🫶", created_at: "2026-02-25T15:02:00Z", sender: { first_name: "Zoe", last_name: "Foster", avatar_url: null } },
  ],
  "demo-group-mens": [
    { id: "mm1", user_id: "demo-james", content: "Hey men, just wanted to check in. How's everyone doing this week?", created_at: "2026-02-25T07:30:00Z", sender: { first_name: "James", last_name: "Whitfield", avatar_url: null } },
    { id: "mm2", user_id: "demo-marcus", content: "Honestly been a tough week at work. Appreciate you asking, Pastor.", created_at: "2026-02-25T07:45:00Z", sender: { first_name: "Marcus", last_name: "Johnson", avatar_url: null } },
    { id: "mm3", user_id: "demo-david", content: "Praying for you Marcus. Anything specific we can lift up?", created_at: "2026-02-25T07:52:00Z", sender: { first_name: "David", last_name: "Chen", avatar_url: null } },
    { id: "mm4", user_id: "demo-marcus", content: "Just wisdom and patience. Boss is making some changes that affect my whole team. Trying to lead well through it.", created_at: "2026-02-25T08:01:00Z", sender: { first_name: "Marcus", last_name: "Johnson", avatar_url: null } },
    { id: "mm5", user_id: "demo-joshua", content: "Been there man. Romans 8:28 got me through a similar season last year.", created_at: "2026-02-25T08:10:00Z", sender: { first_name: "Joshua", last_name: "Brooks", avatar_url: null } },
    { id: "mm6", user_id: "demo-james", content: "Good word Joshua. Marcus, let's grab coffee this week — I'd love to hear more and pray with you.", created_at: "2026-02-25T08:15:00Z", sender: { first_name: "James", last_name: "Whitfield", avatar_url: null } },
    { id: "mm7", user_id: "demo-marcus", content: "Would love that. Thanks guys 🙏", created_at: "2026-02-25T08:20:00Z", sender: { first_name: "Marcus", last_name: "Johnson", avatar_url: null } },
    { id: "mm8", user_id: "demo-caleb", content: "Reminder: basketball this Saturday at 9am at the rec center! Who's coming?", created_at: "2026-02-25T12:00:00Z", sender: { first_name: "Caleb", last_name: "Stewart", avatar_url: null } },
    { id: "mm9", user_id: "demo-ethan", content: "I'll be there 🏀", created_at: "2026-02-25T12:15:00Z", sender: { first_name: "Ethan", last_name: "Lewis", avatar_url: null } },
    { id: "mm10", user_id: "demo-noah", content: "Same! Bringing my brother this time if that's cool", created_at: "2026-02-25T12:22:00Z", sender: { first_name: "Noah", last_name: "Anderson", avatar_url: null } },
    { id: "mm11", user_id: "demo-caleb", content: "The more the merrier! 💪", created_at: "2026-02-25T12:25:00Z", sender: { first_name: "Caleb", last_name: "Stewart", avatar_url: null } },
  ],
  "demo-group-couples": [
    { id: "cm1", user_id: "demo-ruth", content: "Hey couples! Anyone interested in a double date night this Friday?", created_at: "2026-02-24T18:00:00Z", sender: { first_name: "Ruth", last_name: "Phillips", avatar_url: null } },
    { id: "cm2", user_id: "demo-rachel", content: "Yes!! We've been looking for an excuse to get out of the house 😂", created_at: "2026-02-24T18:15:00Z", sender: { first_name: "Rachel", last_name: "Henderson", avatar_url: null } },
    { id: "cm3", user_id: "demo-mike", content: "We're in! Any restaurant suggestions?", created_at: "2026-02-24T18:30:00Z", sender: { first_name: "Michael", last_name: "Patterson", avatar_url: null } },
    { id: "cm4", user_id: "demo-miriam", content: "How about that Italian place downtown? They have great family-style dishes.", created_at: "2026-02-24T18:45:00Z", sender: { first_name: "Miriam", last_name: "Davis", avatar_url: null } },
    { id: "cm5", user_id: "demo-samuel", content: "Seconded! Miriam and I went last month and it was amazing.", created_at: "2026-02-24T19:00:00Z", sender: { first_name: "Samuel", last_name: "Nguyen", avatar_url: null } },
    { id: "cm6", user_id: "demo-sarah", content: "Also — has anyone started the couples devotional Pastor James recommended? David and I just started chapter 2.", created_at: "2026-02-25T09:30:00Z", sender: { first_name: "Sarah", last_name: "Mitchell", avatar_url: null } },
    { id: "cm7", user_id: "demo-aaron", content: "We're on chapter 3! It's really opened up some great conversations for us.", created_at: "2026-02-25T10:00:00Z", sender: { first_name: "Aaron", last_name: "Robinson", avatar_url: null } },
    { id: "cm8", user_id: "demo-ruth", content: "Love hearing that! We should discuss it at the next meetup 📖", created_at: "2026-02-25T10:15:00Z", sender: { first_name: "Ruth", last_name: "Phillips", avatar_url: null } },
  ],
};
