/**
 * Demo/hardcoded data used when ?demo=true is active.
 * This keeps the app showable without real database content.
 */

export const DEMO_SERMON = {
  id: "demo-sermon-1",
  title: "Grace in the Storm",
  date: "February 7, 2026",
  subtitle: "Finding peace amid uncertainty",
  speaker: "Pastor James Whitfield",
  church: "Cornerstone Community Church",
  duration: "48:32",
  videoUrl: null as string | null,
  sourceUrl: null as string | null,
  sourceType: "upload" as const,
  chapters: [
    { title: "Introduction", timestamp: "00:00" },
    { title: "The Story of Peter", timestamp: "07:12" },
    { title: "When the Storm Hits", timestamp: "14:45" },
    { title: "Grace as an Anchor", timestamp: "22:30" },
    { title: "Practical Steps Forward", timestamp: "35:18" },
    { title: "Closing Prayer", timestamp: "44:00" },
  ],
  scriptures: [
    {
      reference: "Matthew 14:27–31",
      text: '"Take courage! It is I. Don\'t be afraid." … "Lord, save me!" Immediately Jesus reached out his hand and caught him.',
    },
    {
      reference: "Ephesians 2:8–9",
      text: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.",
    },
    {
      reference: "Romans 8:28",
      text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    },
  ],
  takeaways: [
    "Grace is not earned — it is a gift that meets us in our storms, not after them.",
    "Like Peter, our eyes fix on the waves instead of Jesus. Refocusing is a daily discipline.",
    "Peace isn't the absence of storms; it's the presence of God within them.",
    "Every storm has a purpose — God uses uncertainty to deepen our trust.",
    "Community is part of God's design for resilience. Don't face the storm alone.",
  ],
  reflectionQuestions: [
    "Where in your life right now are you feeling like Peter — sinking and afraid? What does it look like to cry out, 'Lord, save me'?",
    "Think of a past storm that God brought you through. How did that season shape your faith?",
    "In what area of your life do you need to shift your focus from the waves to Jesus this week?",
    "How does knowing grace is a gift — not earned — change the way you approach God when you feel like you've failed?",
    "Who in your community is in a storm right now? How can you reach out to them this week?",
  ],
  spark: "Grace meets you in the storm, not on the other side of it.",
  weeklyChallenge:
    "This week, write down one fear that's been keeping you from trusting God fully. Then write a verse of scripture next to it — a promise that speaks directly to that fear.",
  weekendReflection:
    "Look back on this week — what has God been teaching you through this sermon?",
};

export const DEMO_PREVIOUS_SERMONS: typeof DEMO_SERMON[] = [
  {
    id: "demo-sermon-2",
    title: "You Are Already Enough",
    date: "January 31, 2026",
    subtitle: "Resting in your God-given identity",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "42:15",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "The Lie of Performance", timestamp: "06:30" },
      { title: "What God Says About You", timestamp: "13:20" },
      { title: "Replacing the Lies", timestamp: "24:00" },
      { title: "Closing Prayer", timestamp: "38:45" },
    ],
    scriptures: [
      { reference: "Psalm 139:14", text: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well." },
      { reference: "Ephesians 1:4–5", text: "For he chose us in him before the creation of the world to be holy and blameless in his sight. In love he predestined us for adoption." },
    ],
    takeaways: [
      "Your identity is not determined by what you do, but by Whose you are.",
      "Performance-based faith exhausts us — grace invites us to rest.",
      "Replacing lies with scripture is a daily, intentional practice.",
      "God's love is not conditional on your productivity or success.",
    ],
    reflectionQuestions: [
      "Where are you striving to earn something God has already freely given?",
      "What lie about your identity have you been believing? What does scripture say instead?",
      "How would your week look different if you truly believed you were enough?",
    ],
    spark: "You don't have to earn what God has already freely given.",
    weeklyChallenge: "Write down one lie you've believed about yourself, then find a verse that speaks the truth. Read it aloud every morning this week.",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
  {
    id: "demo-sermon-3",
    title: "The Power of Small Steps",
    date: "January 24, 2026",
    subtitle: "Faithfulness in the everyday moments",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "39:50",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "David & Goliath Revisited", timestamp: "05:00" },
      { title: "Small Obediences", timestamp: "12:40" },
      { title: "Building Momentum", timestamp: "22:15" },
      { title: "Closing Prayer", timestamp: "36:00" },
    ],
    scriptures: [
      { reference: "Zechariah 4:10", text: "Do not despise these small beginnings, for the LORD rejoices to see the work begin." },
      { reference: "Luke 16:10", text: "Whoever can be trusted with very little can also be trusted with much." },
    ],
    takeaways: [
      "God is not looking for grand gestures — He is looking for faithful small steps.",
      "Every small act of obedience builds trust between you and God.",
      "Don't wait for the perfect moment. Start where you are.",
      "Momentum is built one faithful decision at a time.",
    ],
    reflectionQuestions: [
      "What small step of obedience have you been putting off?",
      "Where in your life are you waiting for a 'big moment' instead of being faithful now?",
      "How can you celebrate small wins with God this week?",
    ],
    spark: "Don't despise small beginnings — God starts big things in small places.",
    weeklyChallenge: "Identify one small spiritual habit — 5 minutes of prayer, one verse a day — and do it every day this week without skipping.",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
  {
    id: "demo-sermon-4",
    title: "When God Feels Distant",
    date: "January 17, 2026",
    subtitle: "Navigating seasons of spiritual dryness",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "45:00",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "The Psalms of Lament", timestamp: "08:00" },
      { title: "Spiritual Dryness is Normal", timestamp: "17:30" },
      { title: "Practices That Draw Us Near", timestamp: "28:00" },
      { title: "Closing Prayer", timestamp: "41:00" },
    ],
    scriptures: [
      { reference: "Psalm 22:1", text: "My God, my God, why have you forsaken me? Why are you so far from saving me, so far from my cries of anguish?" },
      { reference: "James 4:8", text: "Come near to God and he will come near to you." },
    ],
    takeaways: [
      "Feeling distant from God is not evidence that He has left — it is an invitation to draw near.",
      "The Psalms give us permission to be honest with God in every season.",
      "Spiritual disciplines are not about earning God's presence — they create space to receive it.",
      "Dry seasons often precede breakthrough seasons.",
    ],
    reflectionQuestions: [
      "Are you in a dry season right now? What does it feel like?",
      "What practice could you add this week to draw nearer to God?",
      "How have past dry seasons shaped your faith in ways you didn't expect?",
    ],
    spark: "God has not moved. He is closer than you think.",
    weeklyChallenge: "Spend 10 minutes in silence each morning this week — no music, no phone — just sitting with God and letting Him speak.",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
  {
    id: "demo-sermon-5",
    title: "Forgiveness Is a Practice",
    date: "January 10, 2026",
    subtitle: "Learning to release what we were never meant to carry",
    speaker: "Pastor James Whitfield",
    church: "Cornerstone Community Church",
    duration: "51:20",
    videoUrl: null,
    sourceUrl: null,
    sourceType: "upload",
    chapters: [
      { title: "Introduction", timestamp: "00:00" },
      { title: "The Weight of Unforgiveness", timestamp: "07:00" },
      { title: "The Parable of the Prodigal Son", timestamp: "15:00" },
      { title: "Forgiveness is Not Excusing", timestamp: "28:00" },
      { title: "Steps Toward Freedom", timestamp: "40:00" },
      { title: "Closing Prayer", timestamp: "48:00" },
    ],
    scriptures: [
      { reference: "Ephesians 4:31–32", text: "Get rid of all bitterness, rage and anger… Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you." },
      { reference: "Matthew 6:14", text: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you." },
    ],
    takeaways: [
      "Unforgiveness is a weight we were never designed to carry.",
      "Forgiveness is not excusing the wrong — it is releasing your right to revenge.",
      "You may need to choose forgiveness daily before it becomes a feeling.",
      "Forgiving others is an act of trusting God with justice.",
    ],
    reflectionQuestions: [
      "Is there someone in your life you haven't fully forgiven?",
      "What would it feel like to release that person to God today?",
      "How has God's forgiveness of you changed the way you see others?",
    ],
    spark: "Forgiveness is not a feeling — it's a decision to stop carrying what God never asked you to hold.",
    weeklyChallenge: "Write a letter to someone you need to forgive — you don't have to send it. Just write what you felt and then write: 'I release this to God.'",
    weekendReflection: "Look back on this week — what has God been teaching you through this sermon?",
  },
];

export const DEMO_JOURNAL_ENTRIES = [
  {
    id: "1",
    date: "Feb 10, 2026",
    type: "sermon" as const,
    tag: "Sermon",
    preview: "The part about Peter stepping out of the boat really stayed with me. I've been clinging to the boat in my own life — staying safe instead of trusting...",
    sermonTitle: "Grace in the Storm",
    bookmarked: true,
    fullText: "The part about Peter stepping out of the boat really stayed with me. I've been clinging to the boat in my own life — staying safe instead of trusting God with the uncertainty. Pastor James asked where we're looking, and I realized I've been staring at the waves of my job situation. Today I'm choosing to look up.",
    suggestedScripture: {
      reference: "Matthew 14:29",
      text: '"Come," he said. Then Peter got down out of the boat, walked on the water and came toward Jesus.',
    },
  },
  {
    id: "2",
    date: "Feb 8, 2026",
    type: "challenge" as const,
    tag: "Challenge",
    preview: "I wrote down my fear: 'That I'm not enough.' Next to it I put Romans 8:38–39. I read it three times and something...",
    sermonTitle: "Grace in the Storm",
    bookmarked: false,
    fullText: "I wrote down my fear: 'That I'm not enough.' Next to it I put Romans 8:38–39. I read it three times and something shifted. I am convinced that nothing in all creation can separate me from the love of God. That's not me — that's the Word. I'm holding onto this.",
    suggestedScripture: {
      reference: "Romans 8:38–39",
      text: "For I am convinced that neither death nor life, neither angels nor demons… shall be able to separate us from the love of God.",
    },
  },
  {
    id: "3",
    date: "Jan 31, 2026",
    type: "sermon" as const,
    tag: "Sermon",
    preview: "The series on identity hit differently this week. I keep performing for God instead of resting in who He says I am. Working on it...",
    sermonTitle: "You Are Already Enough",
    bookmarked: true,
    fullText: "The series on identity hit differently this week. I keep performing for God instead of resting in who He says I am. Working on replacing the lies with truth — one day at a time.",
    suggestedScripture: {
      reference: "Psalm 139:14",
      text: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.",
    },
  },
];
